#!/usr/bin/env bash

# herbst start

hc() {
    herbstclient "$@"
}
hc emit_hook reload
xsetroot -solid '#0d0e0f'
hc keyunbind --all

# main keys

Mod=Mod1 

hc keybind $Mod-Escape quit
hc keybind $Mod-c reload
hc keybind $Mod-q close
hc keybind $Mod-Return spawn alacritty
hc keybind $Mod-d spawn rofi -show drun
hc keybind $Mod-p spawn i3lock-fancy

# client focus and movement

hc keybind $Mod-BackSpace   cycle_monitor
hc keybind $Mod-Tab         cycle_all +1
hc keybind $Mod-Shift-Tab   cycle_all -1

hc keybind $Mod-h     focus left
hc keybind $Mod-j     focus down
hc keybind $Mod-k     focus up
hc keybind $Mod-l     focus right

hc keybind $Mod-Shift-h     shift left
hc keybind $Mod-Shift-j     shift down
hc keybind $Mod-Shift-k     shift up
hc keybind $Mod-Shift-l     shift right

# layouting

hc keybind $Mod-u       split   bottom  0.5
hc keybind $Mod-o       split   right   0.5
hc keybind $Mod-r remove
hc keybind $Mod-space set_attr clients.focus.floating toggle
hc keybind $Mod-f fullscreen toggle

resizestep=0.05

hc keybind $Mod-Control-h       resize left +$resizestep
hc keybind $Mod-Control-j       resize down +$resizestep
hc keybind $Mod-Control-k       resize up +$resizestep
hc keybind $Mod-Control-l       resize right +$resizestep

# workspaces

tag_names=( {1..4} )
tag_keys=( {1..4} 0 )

hc rename default "${tag_names[0]}" || true
for i in "${!tag_names[@]}" ; do
    hc add "${tag_names[$i]}"
    key="${tag_keys[$i]}"
    if [ -n "$key" ] ; then
        hc keybind "$Mod-$key" use_index "$i"
        hc keybind "$Mod-Shift-$key" move_index "$i"
    fi
done

# mouse

hc mouseunbind --all
hc mousebind $Mod-Button1 move
hc mousebind $Mod-Button2 zoom
hc mousebind $Mod-Button3 resize

# theme

hc attr theme.tiling.reset 1
hc attr theme.floating.reset 1
hc set frame_border_active_color '#222222'
hc set frame_border_normal_color '#101010'
hc set frame_bg_normal_color '#0d0e0f'
hc set frame_bg_active_color '#32302f'
hc set frame_border_width 0
hc set show_frame_decorations 'focused_if_multiple'
hc set frame_bg_transparent off
hc set frame_transparent_width 2
hc set frame_gap 8

hc attr theme.title_when never
hc attr theme.title_height 15
hc attr theme.title_font 'Fira Sans:pixelsize=12'
hc attr theme.title_depth 3
hc attr theme.title_color '#282828'

hc attr theme.active.color '#fabd2f'
hc attr theme.normal.color '#282828'
hc attr theme.urgent.color '#fb4934'

hc attr theme.tab_color '#1F1F1F'
hc attr theme.active.tab_color '#2B4F0A'
hc attr theme.active.tab_outer_color '#6C8257'
hc attr theme.active.tab_title_color '#ababab'

hc attr theme.inner_width 0
hc attr theme.inner_color black
hc attr theme.active.inner_color '#789161'
hc attr theme.urgent.inner_color '#9A65B0'
hc attr theme.normal.inner_color '#606060'

for state in active urgent normal ; do
    hc substitute C theme.${state}.inner_color \
        attr theme.${state}.outer_color C
done
hc attr theme.tiling.outer_width 0

hc attr theme.normal.title_color '#898989'
hc attr theme.border_width 2
hc attr theme.floating.border_width 2
hc attr theme.floating.outer_width 0
hc attr theme.floating.outer_color black

hc attr theme.background_color '#0d0e0f'

hc set window_gap 0
hc set frame_padding 0
hc set smart_window_surroundings off
hc set smart_frame_surroundings on
hc set mouse_recenter_gap 0

# rules

hc unrule -F
#hc rule class=Alacritty tag=3 # move all xterms to tag 3
hc rule focus=on 
hc rule floatplacement=smart
hc rule windowtype~'_NET_WM_WINDOW_TYPE_(DIALOG|UTILITY|SPLASH)' floating=on
hc rule windowtype='_NET_WM_WINDOW_TYPE_DIALOG' focus=on
hc rule windowtype~'_NET_WM_WINDOW_TYPE_(NOTIFICATION|DOCK|DESKTOP)' manage=off
hc rule fixedsize floating=on
hc set tree_style '╾│ ├└╼─┐'

# autostart

pkill polybar; polybar &
picom &

# herbst end

hc unlock
hc detect_monitors
